###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Teknolog Informasi",
    "username": "admin",
    "password": "admin",
    "email": "teknoinfor@mail.com",
    "role": "ADMINISTRATOR"
}