###
GET http://localhost:3000/dosen
Content-Type: application/json

###
GET http://localhost:3000/dosen/:kode
Content-Type: application/json

###
POST http://localhost:3000/dosen
Content-Type: application/json

{
    "dosen_kode": "AI",
    "dosen_nama": "Annissaa Indrawati",
    "dosen_level": 2,
    "kesediaan": [
        { "hari": "SENIN", "sesi": "DUA" },
        { "hari": "SELASA", "sesi": "SATU" },
        { "hari": "RABU", "sesi": "DUA" }      
    ]
}

###
PATCH http://localhost:3000/dosen/:kode
Content-Type: application/json

{
    "dosen_kode" : "HC",
    "dosen_nama" : "Henning Titi Ciptyaningtyas",
    "dosen_level" : 3,
    "kesediaan": [
        { "hari": "SENIN", "sesi": "SATU" },
        { "hari": "SENIN", "sesi": "DUA" },
        { "hari": "SELASA", "sesi": "SATU" },
        { "hari": "RABU", "sesi": "SATU" },
        { "hari": "KAMIS", "sesi": "SATU" },
        { "hari": "JUMAT", "sesi": "SATU" }
    ]
}

###
DELETE http://localhost:3000/dosen/:kode
Content-Type: application/json