@token = <ubah token>

###
GET http://localhost:3000/jadwal_hindari
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/jadwal_hindari
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "hindari_agenda" : "KALKULUS 2",
    "hindari_hari" : "SELASA",
    "hindari_sesi" : "DUA",
    "hindari_smt" : [4]
}

###
PATCH http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "hindari_agenda" : "Pengayaan",
    "hindari_hari" : "JUMAT",
    "hindari_sesi" : "DUA",
    "hindari_smt" : [1, 2, 4]
}

###
DELETE http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json
Authorization: Bearer {{token}}