###
GET http://localhost:3000/jadwal_hindari
Content-Type: application/json

###
GET http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json

###
POST http://localhost:3000/jadwal_hindari
Content-Type: application/json

{
    "hindari_agenda" : "SKPB",
    "hindari_hari" : "JUMAT",
    "hindari_sesi" : "TIGA",
    "hindari_smt" : [1, 2, 3]
}

###
PATCH http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json

{
    "hindari_agenda" : "Pengayaan",
    "hindari_hari" : "JUMAT",
    "hindari_sesi" : "DUA",
    "hindari_smt" : [1, 2, 4]
}

###
DELETE http://localhost:3000/jadwal_hindari/:id
Content-Type: application/json