###
GET http://localhost:3000/mata_kuliah
Content-Type: application/json

###
GET http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json

###
POST http://localhost:3000/mata_kuliah
Content-Type: application/json

{
    "matkul_kode" : "ET123456",
    "matkul_nama" : "Struktur Data",
    "matkul_sem" : 4,
    "matkul_tipe" : "DEPARTEMEN",
    "kelas": [
        { "kelas_mk": "A" },
        { "kelas_mk": "B" }
    ]
}

###
PATCH http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json

{
    "matkul_kode" : "ET234602",
    "matkul_nama" : "Pengembangan Sistem dan Teknologi Informasi (Capstone Project)",
    "matkul_sem" : 6,
    "matkul_tipe" : "PENGAYAAN",
    "kelas": [
        { "kelas_mk": "A" },
        { "kelas_mk": "B" }
    ]
}

###
DELETE http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json