@token = <ubah token>

###
GET http://localhost:3000/mata_kuliah
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/mata_kuliah
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "matkul_kode" : "ET234814",
    "matkul_nama" : "Sistem Cerdas",
    "kelas": [
        { "kelas_mk": "A" }
    ]
}

###
PATCH http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "matkul_kode" : "ET234602",
    "matkul_nama" : "Pengembangan Sistem dan Teknologi Informasi (Capstone Project)",
    "kelas": [
        { "kelas_mk": "A" },
        { "kelas_mk": "B" }
    ]
}

###
DELETE http://localhost:3000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}