@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzliNmU5LWYzZDUtNDliZC1hZmZlLWY3ZjAyMzE2N2NhMSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiQURNSU5JU1RSQVRPUiIsInRva2VuVHlwZSI6ImFjY2VzcyIsImlhdCI6MTc0NjcyNTA1OSwiZXhwIjoxNzQ2NzQ2NjU5fQ.V5QteaqkteLTzz1HgQABWsCs_-IKlRyoUhNEOnKppF0

###
GET http://localhost:5000/mata_kuliah
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:5000/mata_kuliah
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "matkul_kode" : "ET234814",
    "matkul_nama" : "Sistem Cerdas",
    "kelas": [
        { "kelas_mk": "A" }
    ]
}

###
PATCH http://localhost:5000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "matkul_kode" : "ET234602",
    "matkul_nama" : "Pengembangan Sistem dan Teknologi Informasi (Capstone Project)",
    "kelas": [
        { "kelas_mk": "A" },
        { "kelas_mk": "B" }
    ]
}

###
DELETE http://localhost:5000/mata_kuliah/:kode
Content-Type: application/json
Authorization: Bearer {{token}}