@token = <ubah token>

###
GET http://localhost:3000/mk_dosen
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/mk_dosen/:id
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/mk_dosen
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nama_kelas" : "Big Data dan Data Lakehouse B",
    "dosen_kode" : "FD",
    "matkul_tipe" : "DEPARTEMEN",
    "mk_kelas_sem" : [4]
}

###
PUT http://localhost:3000/mk_dosen/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nama_kelas" : "Pengembangan Sistem dan Teknologi Informasi (Capstone Project) A",
    "dosen_kode" : "HC",
    "matkul_tipe" : "PENGAYAAN",
    "mk_kelas_sem" : [1, 2, 3]
}

###
DELETE http://localhost:3000/mk_dosen/:id
Content-Type: application/json
Authorization: Bearer {{token}}