@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQ1MDQyMTYwLCJleHAiOjE3NDUwNjM3NjB9.mfr9UfNQhwfVR0h2UJquRv-rIa5hjvakYM-JZVcNAyk

###
GET http://localhost:3000/ruangan
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/ruangan/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/ruangan
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ruangan_kode" : "705",
    "ruangan_kapasitas" : 48
}

###
PATCH http://localhost:3000/ruangan/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ruangan_kode" : "702",
    "ruangan_kapasitas" : 48
}

###
DELETE http://localhost:3000/ruangan/:kode
Content-Type: application/json
Authorization: Bearer {{token}}