@token = <ubah token>

###
GET http://localhost:3000/ruangan
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3000/ruangan/:kode
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:3000/ruangan
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ruangan_kode" : "705",
    "ruangan_kapasitas" : 48
}

###
PATCH http://localhost:3000/ruangan/:702
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ruangan_kode" : "702",
    "ruangan_kapasitas" : 50
}

###
DELETE http://localhost:3000/ruangan/:kode
Content-Type: application/json
Authorization: Bearer {{token}}